version: 0.2

env:
  variables:
    NODE_VERSION: "16"

runtime-versions:
  nodejs: 16

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - sleep 10  


artifacts:
  files: '**/*'
