export const PERMISSION_CONSTANTS = { //add these in db
  // AUTH RELATED PERMISSIONS
  MANAGE_USERS: "MANAGE_USERS",

  // EVENTS LEVEL PERMISSIONS
  ADD_EVENTS: "ADD_EVENTS",
  SETUP_TICKETS: "SETUP_TICKETS",
  EDIT_EVENTS: "EDIT_EVENTS",
  REMOVE_EVENTS: "REMOVE_EVENTS",
  LIST_EVENTS: "LIST_EVENTS",

  PURCHASE_TICKETS: "PURCHASE_TICKETS",
  //TODO : add other permissions
};

export const PUBLIC_ROUTES = {
  FETCH_EVENTS: "FETCH-EVENTS",
};
